matrix:
  include:
    - os: osx
      osx_image: xcode11.2
      language: node_js
      node_js: "12"

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder

# before_install:
#   - sudo sqlite3 "/Library/Application Support/com.apple.TCC/TCC.db" "INSERT INTO access VALUES ('kTCCServiceAccessibility','com.apple.dt.Xcode-Helper',0,1,1,NULL,NULL);"

script: yarn --link-duplicates --pure-lockfile --ignore-engines; yarn test

notifications:
  email: false
before_cache:
   - rm -rf $HOME/.cache/electron-builder/wine
